// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../countyparishdata.js', ['countyparish'], []);
goog.addDependency('../../../googlegeocoder.js', ['goog.ui.AutoComplete.GoogleGeocoder'], ['goog.net.Jsonp', 'goog.ui.AutoComplete', 'goog.ui.AutoComplete.Basic', 'goog.ui.AutoComplete.InputHandler', 'goog.ui.AutoComplete.Renderer', 'goog.userAgent']);
goog.addDependency('../../../main.js', ['nlsgaz'], ['countyparish', 'goog.array', 'goog.debug.Console', 'goog.debug.DivConsole', 'goog.debug.ErrorHandler', 'goog.debug.LogManager', 'goog.debug.Logger', 'goog.dom', 'goog.events.EventType', 'goog.ui.AutoComplete.GoogleGeocoder']);
goog.addDependency('../../../osgaz.js', ['goog.ui.AutoComplete.OSGaz'], ['goog.net.Jsonp', 'goog.ui.AutoComplete', 'goog.ui.AutoComplete.Basic', 'goog.ui.AutoComplete.InputHandler', 'goog.ui.AutoComplete.OSGazMatcher', 'goog.ui.AutoComplete.Renderer']);
goog.addDependency('../../../osgazmatcher.js', ['goog.ui.AutoComplete.OSGazMatcher'], ['goog.Disposable', 'goog.Timer', 'goog.Uri', 'goog.events', 'goog.json', 'goog.net.Jsonp', 'goog.ui.AutoComplete']);
